version: 2
jobs:
  build:
      working_directory: ~/twitter
      docker:
          - image: circleci/node:12.14.1-browsers
          - image: mongo:4.2
      steps:
          # Checkout codebase from the branch into working_directory
          - checkout
          # Log the current branch
          - run:
              name: Show current branch
              command: echo ${CIRCLE_BRANCH}
          # Install and Cache dependencies
          - run: npm install
          - restore_cache:
              key: dependency-cache-{{ checksum "package.json" }}
          - save_cache:
              key: dependency-cache-{{ checksum "package.json" }}
              paths:
                - ./node_modules
          # Test the source code
          - run: npm test
          - store_artifacts:
              path: test-results.xml
              prefix: tests
          - store_artifacts:
              path: coverage
              prefix: coverage
          - store_test_results:
              path: test-results.xml
                           
        
workflows:
    version: 2
    build:
        jobs:
          - build